services:
  - type: web
    name: n8n
    env: docker
    plan: free
    dockerImage: n8nio/n8n:latest
    envVars:
      - key: N8N_BASIC_AUTH_ACTIVE
        value: true
      - key: N8N_BASIC_AUTH_USER
        value: admin
      - key: N8N_BASIC_AUTH_PASSWORD
        value: Kainisthbest@1979
      - key: N8N_ENCRYPTION_KEY
        value: b59d9xh95dhf9879fdsh789d78dsh9f
      - key: WEBHOOK_URL
        value: https://n8n-padel.onrender.com/
      - key: GENERIC_TIMEZONE
        value: Europe/Bucharest
